### ISSUE TITLE
Correct font is not displayed in Browse

### ISSUE THREAD

**Issue by inkyfingers** [inkyfingers/gallery#1]
Remark tries to optimize the "fill" of slides containing screen shots, but authors need to keep line lengths to a minimum sometimes. We want a tall font to reduce line length. Times New Roman is an acceptable compromise.
When viewed in Browse [v. 157.1] the specified font is not used.

**Comment by venky18** [comment]
please keep the source code and issues in same repository.

**Comment by inkyfingers** [comment]
Sorry for any inconvenience. I guess I have the issue filed in Master, and the source code in the gh-pages branch here. I was treating this as the work-in-progress repository, although I have (perhaps inappropriately) duplicated it at www-sugarlabs in order to test it in a possible context.

**Comment by venky18** [comment]
I don't think times new roman is a good choice have a look at  [Dosis](https://www.google.com/fonts/specimen/Dosis) and https://www.google.com/fonts

**Comment by inkyfingers** [comment]
@venky18, thanks for this suggestion. Fonts is a big subject for the www-sugarlabs project in general.
Did you test Dosis against: **When viewed in Browse the specified font is not used?**

**Comment by inkyfingers** [comment]
For reference: [DejaVu LGC Sans](http://dejavu-fonts.org/wiki/Main_Page) is the default font in Sugar.

http://wiki.sugarlabs.org/go/Human_Interface_Guidelines/The_Sugar_Interface/Text_and_Fonts

I have drawn attention to the font issue in case it is relevant to #2.

### Edit:

I will test the effect of changing the specified font to dejavu.

**Comment by inkyfingers** [comment]
Use DejaVu Sans.
